<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <SonarQubeExclude>true</SonarQubeExclude>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authorization" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\NEvo.Core\NEvo.Core.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Ddd.EventSourcing\NEvo.Ddd.EventSourcing.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Messaging\NEvo.Messaging.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Messaging.Authorization\NEvo.Messaging.Authorization.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Messaging.Cqrs\NEvo.Messaging.Cqrs.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Messaging.Web\NEvo.Messaging.Web.csproj" />
    <ProjectReference Include="..\NEvo.ExampleApp.Orchestration\NEvo.ExampleApp.Orchestration.ServiceDefaults\NEvo.ExampleApp.Orchestration.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
