/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as SpecLayoutRouteImport } from './routes/_spec-layout.tsx'
import { Route as SpecLayoutIndexRouteImport } from './routes/_spec-layout/index.tsx'
import { Route as SpecLayoutArchiveRouteImport } from './routes/_spec-layout/archive.tsx'
import { Route as SpecLayoutSpecsSourceSlugRouteImport } from './routes/_spec-layout/specs.$source.$slug.tsx'
import { Route as SpecsSourceSlugSessionsProviderProviderSessionIdRouteImport } from './routes/specs.$source.$slug.sessions.$provider.$providerSessionId.tsx'

const SpecLayoutRoute = SpecLayoutRouteImport.update({
  id: '/_spec-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecLayoutIndexRoute = SpecLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpecLayoutRoute,
} as any)
const SpecLayoutArchiveRoute = SpecLayoutArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => SpecLayoutRoute,
} as any)
const SpecLayoutSpecsSourceSlugRoute =
  SpecLayoutSpecsSourceSlugRouteImport.update({
    id: '/specs/$source/$slug',
    path: '/specs/$source/$slug',
    getParentRoute: () => SpecLayoutRoute,
  } as any)
const SpecsSourceSlugSessionsProviderProviderSessionIdRoute =
  SpecsSourceSlugSessionsProviderProviderSessionIdRouteImport.update({
    id: '/specs/$source/$slug/sessions/$provider/$providerSessionId',
    path: '/specs/$source/$slug/sessions/$provider/$providerSessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SpecLayoutIndexRoute
  '/archive': typeof SpecLayoutArchiveRoute
  '/specs/$source/$slug': typeof SpecLayoutSpecsSourceSlugRoute
  '/specs/$source/$slug/sessions/$provider/$providerSessionId': typeof SpecsSourceSlugSessionsProviderProviderSessionIdRoute
}
export interface FileRoutesByTo {
  '/archive': typeof SpecLayoutArchiveRoute
  '/': typeof SpecLayoutIndexRoute
  '/specs/$source/$slug': typeof SpecLayoutSpecsSourceSlugRoute
  '/specs/$source/$slug/sessions/$provider/$providerSessionId': typeof SpecsSourceSlugSessionsProviderProviderSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_spec-layout': typeof SpecLayoutRouteWithChildren
  '/_spec-layout/archive': typeof SpecLayoutArchiveRoute
  '/_spec-layout/': typeof SpecLayoutIndexRoute
  '/_spec-layout/specs/$source/$slug': typeof SpecLayoutSpecsSourceSlugRoute
  '/specs/$source/$slug/sessions/$provider/$providerSessionId': typeof SpecsSourceSlugSessionsProviderProviderSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/specs/$source/$slug'
    | '/specs/$source/$slug/sessions/$provider/$providerSessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/archive'
    | '/'
    | '/specs/$source/$slug'
    | '/specs/$source/$slug/sessions/$provider/$providerSessionId'
  id:
    | '__root__'
    | '/_spec-layout'
    | '/_spec-layout/archive'
    | '/_spec-layout/'
    | '/_spec-layout/specs/$source/$slug'
    | '/specs/$source/$slug/sessions/$provider/$providerSessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SpecLayoutRoute: typeof SpecLayoutRouteWithChildren
  SpecsSourceSlugSessionsProviderProviderSessionIdRoute: typeof SpecsSourceSlugSessionsProviderProviderSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_spec-layout': {
      id: '/_spec-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SpecLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_spec-layout/': {
      id: '/_spec-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SpecLayoutIndexRouteImport
      parentRoute: typeof SpecLayoutRoute
    }
    '/_spec-layout/archive': {
      id: '/_spec-layout/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof SpecLayoutArchiveRouteImport
      parentRoute: typeof SpecLayoutRoute
    }
    '/_spec-layout/specs/$source/$slug': {
      id: '/_spec-layout/specs/$source/$slug'
      path: '/specs/$source/$slug'
      fullPath: '/specs/$source/$slug'
      preLoaderRoute: typeof SpecLayoutSpecsSourceSlugRouteImport
      parentRoute: typeof SpecLayoutRoute
    }
    '/specs/$source/$slug/sessions/$provider/$providerSessionId': {
      id: '/specs/$source/$slug/sessions/$provider/$providerSessionId'
      path: '/specs/$source/$slug/sessions/$provider/$providerSessionId'
      fullPath: '/specs/$source/$slug/sessions/$provider/$providerSessionId'
      preLoaderRoute: typeof SpecsSourceSlugSessionsProviderProviderSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SpecLayoutRouteChildren {
  SpecLayoutArchiveRoute: typeof SpecLayoutArchiveRoute
  SpecLayoutIndexRoute: typeof SpecLayoutIndexRoute
  SpecLayoutSpecsSourceSlugRoute: typeof SpecLayoutSpecsSourceSlugRoute
}

const SpecLayoutRouteChildren: SpecLayoutRouteChildren = {
  SpecLayoutArchiveRoute: SpecLayoutArchiveRoute,
  SpecLayoutIndexRoute: SpecLayoutIndexRoute,
  SpecLayoutSpecsSourceSlugRoute: SpecLayoutSpecsSourceSlugRoute,
}

const SpecLayoutRouteWithChildren = SpecLayoutRoute._addFileChildren(
  SpecLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SpecLayoutRoute: SpecLayoutRouteWithChildren,
  SpecsSourceSlugSessionsProviderProviderSessionIdRoute:
    SpecsSourceSlugSessionsProviderProviderSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
