<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <SonarQubeExclude>true</SonarQubeExclude>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/NEvo.Ddd.EventSourcing/NEvo.Ddd.EventSourcing.csproj" />
    <ProjectReference Include="../../../src/NEvo.Messaging.Authorization/NEvo.Messaging.Authorization.csproj" />
    <ProjectReference Include="../../../src/NEvo.Web.Authorization/NEvo.Web.Authorization.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Core\NEvo.Core.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.EntityFramework\NEvo.EntityFramework.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Messaging.Cqrs\NEvo.Messaging.Cqrs.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Messaging.EntityFramework\NEvo.Messaging.EntityFramework.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Messaging.Web\NEvo.Messaging.Web.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Messaging\NEvo.Messaging.csproj" />
    <ProjectReference Include="..\..\..\src\NEvo.Web\NEvo.Web.csproj" />
    <ProjectReference Include="..\NEvo.ExampleApp.Orchestration\NEvo.ExampleApp.Orchestration.ServiceDefaults\NEvo.ExampleApp.Orchestration.ServiceDefaults.csproj" />
    <ProjectReference Include="..\NEvo.ExampleApp.ServiceB.Api\NEvo.ExampleApp.ServiceB.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExampleDomain/Documents/" />
  </ItemGroup>

</Project>
