<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NEvo.ExampleApp.Identity.Api\NEvo.ExampleApp.Identity.Api.csproj" />
    <ProjectReference Include="..\..\NEvo.ExampleApp.ServiceA.Api\NEvo.ExampleApp.ServiceA.Api.csproj" />
    <ProjectReference Include="..\..\NEvo.ExampleApp.ServiceB.Api\NEvo.ExampleApp.ServiceB.Api.csproj" />
  </ItemGroup>

</Project>
