#!/usr/bin/env node
// GENERATED BY: human-written — do not mark as generated.
// tools/docs.mjs — documentation index and validation CLI
// Usage: node tools/docs.mjs <generate|validate|check|find>

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(import.meta.url), '../..');
const DOCS_DIR = join(ROOT, 'docs');
const INDEX_JSON = join(DOCS_DIR, 'index.generated.json');
const INDEX_MD = join(DOCS_DIR, 'index.generated.md');

const REQUIRED_FIELDS = {
  architecture: ['id', 'type', 'title', 'status', 'scope', 'read_when', 'summary'],
  development:  ['id', 'type', 'title', 'status', 'summary'],
  adr:          ['id', 'type', 'title', 'status', 'date'],
  ai:           ['id', 'type', 'title', 'status', 'summary'],
  change:       ['id', 'type', 'title', 'status', 'change'],
};

// ── YAML front matter parser (subset: flat keys, string lists, multiline >) ──

function parseFrontMatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return null;
  return parseYamlSubset(match[1]);
}

function parseYamlSubset(text) {
  const obj = {};
  const lines = text.split(/\r?\n/);
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];
    if (!line.trim() || line.trim().startsWith('#')) { i++; continue; }

    const colon = line.indexOf(':');
    if (colon === -1) { i++; continue; }

    const key = line.slice(0, colon).trim();
    const rest = line.slice(colon + 1).trim();
    i++;

    if (rest === '' || rest === '>') {
      // Look ahead for list or multiline
      const next = lines[i];
      if (!next) { obj[key] = null; continue; }
      const nextIndent = next.match(/^(\s*)/)[1].length;

      if (next.trim().startsWith('- ')) {
        const arr = [];
        while (i < lines.length) {
          const l = lines[i];
          if (!l || !l.trim()) { i++; continue; }
          if (l.match(/^(\s*)/)[1].length < nextIndent) break;
          if (l.trim().startsWith('- ')) arr.push(l.trim().slice(2).trim());
          i++;
        }
        obj[key] = arr;
      } else if (rest === '>') {
        let value = '';
        while (i < lines.length) {
          const l = lines[i];
          if (!l || !l.trim()) break;
          if (l.match(/^(\s*)/)[1].length < nextIndent) break;
          value += (value ? ' ' : '') + l.trim();
          i++;
        }
        obj[key] = value;
      } else {
        obj[key] = null;
      }
    } else if (rest.startsWith('>')) {
      // Inline folded start
      let value = rest.slice(1).trim();
      const baseIndent = (lines[i] || '').match(/^(\s*)/)[1].length;
      while (i < lines.length) {
        const l = lines[i];
        if (!l || !l.trim()) break;
        if (l.match(/^(\s*)/)[1].length < baseIndent) break;
        value += (value ? ' ' : '') + l.trim();
        i++;
      }
      obj[key] = value;
    } else {
      obj[key] = parseScalar(rest);
    }
  }
  return obj;
}

function parseScalar(s) {
  s = s.trim();
  if (s === 'true') return true;
  if (s === 'false') return false;
  if (s === 'null' || s === '~') return null;
  if (/^-?\d+$/.test(s)) return Number(s);
  if (/^['"].*['"]$/.test(s)) return s.slice(1, -1);
  return s;
}

// ── File scanning ──────────────────────────────────────────────────────────

function walkDir(dir, ext = '.md') {
  if (!existsSync(dir)) return [];
  const results = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) results.push(...walkDir(full, ext));
    else if (extname(entry) === ext && !entry.includes('.generated.')) results.push(full);
  }
  return results;
}

function scanDocs() {
  const files = walkDir(DOCS_DIR);
  const docs = [];
  for (const file of files) {
    const content = readFileSync(file, 'utf8');
    const fm = parseFrontMatter(content);
    if (!fm) continue;
    docs.push({
      file: relative(ROOT, file).replace(/\\/g, '/'),
      ...fm,
    });
  }
  return docs;
}

// ── Validation ─────────────────────────────────────────────────────────────

function validateDocs(docs) {
  const errors = [];
  const ids = new Map();

  for (const doc of docs) {
    const loc = doc.file;

    if (!doc.id) { errors.push(`${loc}: missing 'id'`); continue; }
    if (!doc.type) { errors.push(`${loc}: missing 'type'`); continue; }

    if (ids.has(doc.id)) {
      errors.push(`${loc}: duplicate id '${doc.id}' (also in ${ids.get(doc.id)})`);
    } else {
      ids.set(doc.id, loc);
    }

    const required = REQUIRED_FIELDS[doc.type] || ['id', 'type', 'title', 'status'];
    for (const field of required) {
      if (!doc[field]) errors.push(`${loc}: missing required field '${field}' for type '${doc.type}'`);
    }
  }

  // Validate related/supersedes references
  for (const doc of docs) {
    const refs = [
      ...(Array.isArray(doc.related) ? doc.related : []),
      ...(doc.supersedes ? [doc.supersedes] : []),
      ...(doc.superseded_by ? [doc.superseded_by] : []),
    ].filter(Boolean);

    for (const ref of refs) {
      if (!ids.has(ref)) {
        errors.push(`${doc.file}: unresolved reference '${ref}'`);
      }
    }
  }

  return errors;
}

// ── Index generation ───────────────────────────────────────────────────────

const GENERATED_NOTICE = '<!-- GENERATED FILE — do not edit. Run: node tools/docs.mjs generate -->\n\n';

function generateIndexes(docs) {
  const sorted = [...docs].sort((a, b) => {
    const typeOrder = ['architecture', 'development', 'adr', 'ai', 'change'];
    return (typeOrder.indexOf(a.type) - typeOrder.indexOf(b.type)) || a.id.localeCompare(b.id);
  });

  writeFileSync(INDEX_JSON, JSON.stringify({ generated: new Date().toISOString(), docs: sorted }, null, 2));

  const byType = {};
  for (const doc of sorted) {
    (byType[doc.type] = byType[doc.type] || []).push(doc);
  }

  let md = GENERATED_NOTICE + '# Documentation index\n\n';
  md += `_Generated: ${new Date().toISOString()}_\n\n`;

  for (const [type, typeDocs] of Object.entries(byType)) {
    md += `## ${type.charAt(0).toUpperCase() + type.slice(1)}\n\n`;
    md += '| ID | Title | Status | Scopes |\n|---|---|---|---|\n';
    for (const doc of typeDocs) {
      const scopes = Array.isArray(doc.scope) ? doc.scope.join(', ') : (doc.scope || '');
      md += `| \`${doc.id}\` | [${doc.title}](${doc.file}) | ${doc.status} | ${scopes} |\n`;
    }
    md += '\n';
  }

  writeFileSync(INDEX_MD, md);
  console.log(`Generated: ${relative(ROOT, INDEX_JSON)}`);
  console.log(`Generated: ${relative(ROOT, INDEX_MD)}`);
}

// ── Find ───────────────────────────────────────────────────────────────────

function findDocs(docs, { scope, type, format }) {
  let results = docs;
  if (type) results = results.filter(d => d.type === type);
  if (scope) results = results.filter(d =>
    Array.isArray(d.scope) ? d.scope.includes(scope) : d.scope === scope
  );

  if (format === 'json') {
    console.log(JSON.stringify(results, null, 2));
  } else {
    for (const doc of results) {
      console.log(`${doc.id}  ${doc.file}`);
    }
  }
}

// ── Check (indexes current) ────────────────────────────────────────────────

function checkIndexes(docs) {
  if (!existsSync(INDEX_JSON)) {
    console.error('index.generated.json missing — run: node tools/docs.mjs generate');
    process.exit(1);
  }
  const existing = JSON.parse(readFileSync(INDEX_JSON, 'utf8'));
  const existingIds = new Set(existing.docs.map(d => d.id));
  const currentIds = new Set(docs.map(d => d.id));

  const missing = [...currentIds].filter(id => !existingIds.has(id));
  const extra = [...existingIds].filter(id => !currentIds.has(id));

  if (missing.length || extra.length) {
    if (missing.length) console.error(`Index missing docs: ${missing.join(', ')}`);
    if (extra.length) console.error(`Index has stale docs: ${extra.join(', ')}`);
    console.error('Run: node tools/docs.mjs generate');
    process.exit(1);
  }
  console.log('Indexes are current.');
}

// ── CLI ────────────────────────────────────────────────────────────────────

const [,, cmd, ...args] = process.argv;

const docs = scanDocs();

switch (cmd) {
  case 'generate': {
    const errors = validateDocs(docs);
    if (errors.length) { errors.forEach(e => console.error(e)); process.exit(1); }
    generateIndexes(docs);
    break;
  }
  case 'validate': {
    const errors = validateDocs(docs);
    if (errors.length) { errors.forEach(e => console.error(e)); process.exit(1); }
    console.log(`Validated ${docs.length} documents — no errors.`);
    break;
  }
  case 'check': {
    const errors = validateDocs(docs);
    if (errors.length) { errors.forEach(e => console.error(e)); process.exit(1); }
    checkIndexes(docs);
    break;
  }
  case 'find': {
    const scope = args[args.indexOf('--scope') + 1] || null;
    const type = args[args.indexOf('--type') + 1] || null;
    const format = args[args.indexOf('--format') + 1] || 'text';
    findDocs(docs, { scope, type, format });
    break;
  }
  default:
    console.log('Usage: node tools/docs.mjs <generate|validate|check|find [--scope <scope>] [--type <type>] [--format json]>');
    process.exit(1);
}
