// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NEvo.ExampleApp.Database;

#nullable disable

namespace NEvo.ExampleApp.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20240320221338_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NEvo.Messaging.EntityFramework.Models.InboxProcessedHandler", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HandlerKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId", "HandlerKey");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("MessageId", "HandlerKey"), false);

                    b.HasIndex("ProcessedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ProcessedAt"));

                    b.ToTable("__Inbox_InboxProcessedHandlers", (string)null);
                });

            modelBuilder.Entity("NEvo.Messaging.EntityFramework.Models.InboxProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("MessageId"), false);

                    b.HasIndex("ProcessedAt");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ProcessedAt"));

                    b.ToTable("__Inbox_InboxProcessedMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
